export const SEO_CONFIG = {
  siteUrl: "https://abnjain.me",
  siteName: "Abhinav Jain",
  siteTitle: "Abhinav Jain — Developer, Designer & Best IT Solutionist",
  defaultDescription:
    "Abhinav Jain (abnjain) — Full Stack Developer, Web Designer, SEO Specialist, Cloud Developer, DevOps Specialist & Entrepreneur from Indore, India. Expert in MERN Stack, System Design, and scalable web solutions.",
  defaultImage: "/abhinavjain.png",
  twitterHandle: "@abnjain",
  locale: "en_IN",
  geo: {
    region: "IN-MP",
    placename: "Indore, Madhya Pradesh, India",
    position: "22.7196;75.8577",
    icbm: "22.7196, 75.8577",
  },
  globalKeywords: [
    "Abhinav Jain",
    "abnjain",
    "Developer",
    "Web Developer",
    "Full Stack Developer",
    "MERN Stack Developer",
    "React Developer",
    "Node.js Developer",
    "Next.js Developer",
    "JavaScript Developer",
    "Frontend Developer",
    "Backend Developer",
    "Software Developer",
    "Designer",
    "Web Designer",
    "UI Designer",
    "UX Designer",
    "Frontend Designer",
    "UI/UX Designer",
    "SEO Specialist",
    "SEO Expert",
    "SEO Consultant",
    "Digital Marketing Expert",
    "Search Engine Optimization",
    "Entrepreneur",
    "Tech Entrepreneur",
    "Freelancer",
    "Startup Founder",
    "IT Consultant",
    "System Designer",
    "System Architecture",
    "System Design Expert",
    "Software Architect",
    "Cloud Developer",
    "AWS Developer",
    "Google Cloud Developer",
    "Cloud Infrastructure",
    "Cloud Solutions Architect",
    "DevOps Specialist",
    "DevOps Engineer",
    "CI/CD Expert",
    "Docker",
    "Kubernetes",
    "Infrastructure Engineer",
    "Best IT Solutionist",
    "IT Specialist",
    "IT Solutions Expert",
    "Indore Developer",
    "India Web Developer",
    "Madhya Pradesh Developer",
    "Indian Full Stack Developer",
    "Freelance Developer India",
    "Best Developer Indore",
    "Web Developer Indore",
    "Software Engineer India",
  ],
} as const;
