import Header from "@/Components/Header.js"
import './globals.css'

export const metadata = {
  title: 'Abhinav Jain',
  description: 'Generated by abnjain',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}</body>
    </html>
  )
}
