import Header from "@/Components/Header.js"
import Footer from "@/Components/Footer.js"
import './globals.css'
import 'remixicon/fonts/remixicon.css'

export const metadata = {
  title: 'Abhinav Jain',
  description: 'Generated by abnjain',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  )
}
